version: '3.9'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./public_html:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: <DB NAME> #example db
      MYSQL_USER: <Enter the user> #wss don't use root user
      MYSQL_PASSWORD: <Enter the pass>
      MYSQL_ROOT_PASSWORD: <Enter the root pass> 
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./public_html:/var/www/html
  
  adminer:
    depends_on:
      - mysql
    image: adminer
    restart: always
    ports:
      - 8888:8080

